apiVersion: v1
kind: PersistentVolume
metadata:
  name: app-pv
  namespace: salmahany
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  storageClassName: my-ebs
  hostPath:
    path: /home/salma/oc
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: app-pvc
  namespace: salmahany
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: my-ebs


